### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by avdb13** [blacksky-algorithms/rsky#23]
Can't find examples, contributor guidelines or anything similar but the source code.

**Comment by rudyfraser** [comment]
Contribution guidelines are here: https://github.com/blacksky-algorithms/rsky?tab=readme-ov-file#contribution
If you have any questions or wanna chat about stuff feel free to ping me in the #rust channel of the Bluesky Dev DIscord: https://discord.gg/UGwzQwDPf7

I'm admittedly newer to working in open source so if you think there are things that could be added to the repo to make things clearer, just let me know and I'll try to implement. I know documentation can be better.

Currently the most active development is around rsky-pds and getting it to a state where it can be used in the production network without issues. To get there I've been starting with implementing the same tests used in the canonical typescript implementation.

Generally speaking, besides rsky-feedgen and rsky-firehose, everything should follow closely to the canonical typescript implementation including tests. Differences will be the one noted in the root README where rsky-pds uses postgres, s3 for blobs, and mailgun for mailing.

Thanks for your interest!

**Comment by avdb13** [comment]
> Contribution guidelines are here: https://github.com/blacksky-algorithms/rsky?tab=readme-ov-file#contribution
> If you have any questions or wanna chat about stuff feel free to ping me in the #rust channel of the Bluesky Dev DIscord: https://discord.gg/UGwzQwDPf7
> 
> I'm admittedly newer to working in open source so if you think there are things that could be added to the repo to make things clearer, just let me know and I'll try to implement. I know documentation can be better.
> 
> Currently the most active development is around rsky-pds and getting it to a state where it can be used in the production network without issues. To get there I've been starting with implementing the same tests used in the canonical typescript implementation.
> 
> Generally speaking, besides rsky-feedgen and rsky-firehose, everything should follow closely to the canonical typescript implementation including tests. Differences will be the one noted in the root README where rsky-pds uses postgres, s3 for blobs, and mailgun for mailing.
> 
> Thanks for your interest!

Thank you for providing directions!
