### ISSUE TITLE
Implement Websockets for `com.atproto.sync.subscriberepos`

### ISSUE THREAD

**Issue by DrewMcArthur** [blacksky-algorithms/rsky#7]
## background
see [the spec on event streams and `subscribe` endpoints here](https://atproto.com/specs/event-stream).
see [the `rocket_ws` crate here](https://api.rocket.rs/master/rocket_ws/struct.WebSocket)
see [the `subscription` type in the atproto lexicon here](https://atproto.com/specs/lexicon#subscription-event-stream)

generally, when a client connects to a `subscribe` endpoint ([see here](https://atproto.com/specs/lexicon#primary-type-definitions)), they connect via websockets to listen to events.  they're one way (server -> client), with a few optional parameters including a backfill window or a cursor, allowing the subscriber to catch up on missed messages.

## requirements
- [ ] allow a client to make a web socket connection on any path prefixed with `subscribe` (currently `/xrpc/com.atproto.sync.subscribe_repos` and `/xrpc/com.atproto.label.subscribe_labels`)
- [ ] as records are created within a repo or new labels, send them as messages to any subscribed clients
- [ ] add backfill capabilities (given a parameter in the initial request, start sending messages at some point in the past)

**Comment by DrewMcArthur** [comment]
fyi i've begun work on this in https://github.com/DrewMcArthur/rsky/issues/3

seems like everything runs, i just have to figure out how to test it.

**Comment by rudyfraser** [comment]
Sick! I had also started on this but I'll work on other stuff for now. As an FYI, I generally have been trying to keep the code as close to the TS implementation as possible https://github.com/bluesky-social/atproto/blob/e956ac06be32cbfef06605cda6298b5fd621513a/packages/pds/src/api/com/atproto/sync/subscribeRepos.ts

For testing, you should be able to use a client like Postman to subscribe to your websocket endpoint and in another client do things like create a new account, update the handle, create a new post, etc. and have the messages come through. All of those endpoints exist today under the com.atproto namespaces.

**Comment by rudyfraser** [comment]
Completed this [here](https://github.com/blacksky-algorithms/rsky/commit/edab91edcf56b28cd5710a51e3fc98ea5de06f8c)
